(define (problem autogen)
  (:domain worldsEndAndBeyond)

  (:objects
    Origin cityA cityB cityC cityD cityE cityF cityG cityH cityI cityJ cityK cityL cityM cityN cityO cityP cityQ cityR cityS cityT - city
    hotelA_A hotelB_A hotelC_A hotelD_A hotelE_A hotelF_A hotelG_A hotelH_A hotelI_A hotelJ_A hotelK_A hotelL_A hotelM_A hotelN_A hotelO_A hotelP_A hotelQ_A hotelR_A hotelS_A hotelT_A - hotel
  )

  (:init
    (currentLocation Origin)

    (hotelAt hotelA_A cityA)
    (hotelAt hotelB_A cityB)
    (hotelAt hotelC_A cityC)
    (hotelAt hotelD_A cityD)
    (hotelAt hotelE_A cityE)
    (hotelAt hotelF_A cityF)
    (hotelAt hotelG_A cityG)
    (hotelAt hotelH_A cityH)
    (hotelAt hotelI_A cityI)
    (hotelAt hotelJ_A cityJ)
    (hotelAt hotelK_A cityK)
    (hotelAt hotelL_A cityL)
    (hotelAt hotelM_A cityM)
    (hotelAt hotelN_A cityN)
    (hotelAt hotelO_A cityO)
    (hotelAt hotelP_A cityP)
    (hotelAt hotelQ_A cityQ)
    (hotelAt hotelR_A cityR)
    (hotelAt hotelS_A cityS)
    (hotelAt hotelT_A cityT)

    (flight Origin cityA)
    (flight Origin cityB)
    (flight Origin cityC)
    (flight Origin cityD)
    (flight Origin cityE)
    (flight Origin cityF)
    (flight Origin cityG)
    (flight Origin cityH)
    (flight Origin cityI)
    (flight Origin cityJ)
    (flight Origin cityK)
    (flight Origin cityL)
    (flight Origin cityM)
    (flight Origin cityN)
    (flight Origin cityO)
    (flight Origin cityP)
    (flight Origin cityQ)
    (flight Origin cityR)
    (flight Origin cityS)
    (flight Origin cityT)
    (flight cityA cityO)
    (flight cityB cityL)
    (flight cityC cityD)
    (flight cityD cityB)
    (flight cityE cityB)
    (flight cityF cityR)
    (flight cityG cityN)
    (flight cityH cityP)
    (flight cityI cityM)
    (flight cityJ cityP)
    (flight cityK cityL)
    (flight cityL cityB)
    (flight cityM cityH)
    (flight cityN cityT)
    (flight cityO cityH)
    (flight cityP cityT)
    (flight cityQ cityC)
    (flight cityR cityF)
    (flight cityS cityO)
    (flight cityT cityJ)

    (= (citiesVisited) 0)
    (= (totalDays) 0)
    (= (minDaysInCity) 1)
    (= (maxDaysInCity) 5)

    (= (stayDuration Origin) 0)
    (= (stayDuration cityA) 0)
    (= (stayDuration cityB) 0)
    (= (stayDuration cityC) 0)
    (= (stayDuration cityD) 0)
    (= (stayDuration cityE) 0)
    (= (stayDuration cityF) 0)
    (= (stayDuration cityG) 0)
    (= (stayDuration cityH) 0)
    (= (stayDuration cityI) 0)
    (= (stayDuration cityJ) 0)
    (= (stayDuration cityK) 0)
    (= (stayDuration cityL) 0)
    (= (stayDuration cityM) 0)
    (= (stayDuration cityN) 0)
    (= (stayDuration cityO) 0)
    (= (stayDuration cityP) 0)
    (= (stayDuration cityQ) 0)
    (= (stayDuration cityR) 0)
    (= (stayDuration cityS) 0)
    (= (stayDuration cityT) 0)
    (= (totalcost) 0)
    (= (hotelcost hotelA_A) 122)
    (= (hotelcost hotelB_A) 143)
    (= (hotelcost hotelC_A) 111)
    (= (hotelcost hotelD_A) 220)
    (= (hotelcost hotelE_A) 185)
    (= (hotelcost hotelF_A) 134)
    (= (hotelcost hotelG_A) 163)
    (= (hotelcost hotelH_A) 149)
    (= (hotelcost hotelI_A) 74)
    (= (hotelcost hotelJ_A) 132)
    (= (hotelcost hotelK_A) 115)
    (= (hotelcost hotelL_A) 177)
    (= (hotelcost hotelM_A) 247)
    (= (hotelcost hotelN_A) 129)
    (= (hotelcost hotelO_A) 178)
    (= (hotelcost hotelP_A) 104)
    (= (hotelcost hotelQ_A) 115)
    (= (hotelcost hotelR_A) 243)
    (= (hotelcost hotelS_A) 172)
    (= (hotelcost hotelT_A) 207)

    (= (flightcost Origin cityA) 0)
    (= (flightcost Origin cityB) 0)
    (= (flightcost Origin cityC) 0)
    (= (flightcost Origin cityD) 0)
    (= (flightcost Origin cityE) 0)
    (= (flightcost Origin cityF) 0)
    (= (flightcost Origin cityG) 0)
    (= (flightcost Origin cityH) 0)
    (= (flightcost Origin cityI) 0)
    (= (flightcost Origin cityJ) 0)
    (= (flightcost Origin cityK) 0)
    (= (flightcost Origin cityL) 0)
    (= (flightcost Origin cityM) 0)
    (= (flightcost Origin cityN) 0)
    (= (flightcost Origin cityO) 0)
    (= (flightcost Origin cityP) 0)
    (= (flightcost Origin cityQ) 0)
    (= (flightcost Origin cityR) 0)
    (= (flightcost Origin cityS) 0)
    (= (flightcost Origin cityT) 0)
    (= (flightcost cityA cityO) 180)
    (= (flightcost cityB cityL) 165)
    (= (flightcost cityC cityD) 190)
    (= (flightcost cityD cityB) 127)
    (= (flightcost cityE cityB) 164)
    (= (flightcost cityF cityR) 137)
    (= (flightcost cityG cityN) 138)
    (= (flightcost cityH cityP) 139)
    (= (flightcost cityI cityM) 134)
    (= (flightcost cityJ cityP) 193)
    (= (flightcost cityK cityL) 148)
    (= (flightcost cityL cityB) 158)
    (= (flightcost cityM cityH) 138)
    (= (flightcost cityN cityT) 162)
    (= (flightcost cityO cityH) 128)
    (= (flightcost cityP cityT) 174)
    (= (flightcost cityQ cityC) 198)
    (= (flightcost cityR cityF) 194)
    (= (flightcost cityS cityO) 125)
    (= (flightcost cityT cityJ) 122)

  )

  (:goal
    (and
      (>= (citiesVisited) 20)
      (>= (totalDays) 100)
      (>= (totalcost) 100)
      (<= (totalcost) 1000000)
    )
  )

  (:metric 
    minimize (totalcost)
  )

)
