(define (problem autogen)
  (:domain worldsEndAndBeyond)

  (:objects
    Origin cityA cityB cityC cityD cityE - city
    hotelA_A hotelA_B hotelA_C hotelB_A hotelB_B hotelB_C hotelC_A hotelC_B hotelC_C hotelD_A hotelD_B hotelD_C hotelE_A hotelE_B hotelE_C - hotel
  )

  (:init
    (currentLocation Origin)

    (hotelAt hotelA_A cityA)
    (hotelAt hotelA_B cityA)
    (hotelAt hotelA_C cityA)
    (hotelAt hotelB_A cityB)
    (hotelAt hotelB_B cityB)
    (hotelAt hotelB_C cityB)
    (hotelAt hotelC_A cityC)
    (hotelAt hotelC_B cityC)
    (hotelAt hotelC_C cityC)
    (hotelAt hotelD_A cityD)
    (hotelAt hotelD_B cityD)
    (hotelAt hotelD_C cityD)
    (hotelAt hotelE_A cityE)
    (hotelAt hotelE_B cityE)
    (hotelAt hotelE_C cityE)

    (flight Origin cityA)
    (flight Origin cityB)
    (flight Origin cityC)
    (flight Origin cityD)
    (flight Origin cityE)
    (flight cityA cityB)
    (flight cityA cityC)
    (flight cityA cityE)
    (flight cityB cityA)
    (flight cityB cityD)
    (flight cityB cityE)
    (flight cityC cityA)
    (flight cityC cityB)
    (flight cityC cityE)
    (flight cityD cityB)
    (flight cityD cityC)
    (flight cityD cityE)
    (flight cityE cityB)
    (flight cityE cityC)
    (flight cityE cityD)

    (= (citiesVisited) 0)
    (= (totalDays) 0)
    (= (minDaysInCity) 1)
    (= (maxDaysInCity) 5)

    (= (stayDuration Origin) 0)
    (= (stayDuration cityA) 0)
    (= (stayDuration cityB) 0)
    (= (stayDuration cityC) 0)
    (= (stayDuration cityD) 0)
    (= (stayDuration cityE) 0)
    (= (totalcost) 0)
    (= (hotelcost hotelA_A) 219)
    (= (hotelcost hotelA_B) 203)
    (= (hotelcost hotelA_C) 88)
    (= (hotelcost hotelB_A) 120)
    (= (hotelcost hotelB_B) 207)
    (= (hotelcost hotelB_C) 150)
    (= (hotelcost hotelC_A) 56)
    (= (hotelcost hotelC_B) 96)
    (= (hotelcost hotelC_C) 176)
    (= (hotelcost hotelD_A) 90)
    (= (hotelcost hotelD_B) 169)
    (= (hotelcost hotelD_C) 119)
    (= (hotelcost hotelE_A) 175)
    (= (hotelcost hotelE_B) 54)
    (= (hotelcost hotelE_C) 97)

    (= (flightcost Origin cityA) 0)
    (= (flightcost Origin cityB) 0)
    (= (flightcost Origin cityC) 0)
    (= (flightcost Origin cityD) 0)
    (= (flightcost Origin cityE) 0)
    (= (flightcost cityA cityB) 140)
    (= (flightcost cityA cityC) 124)
    (= (flightcost cityA cityE) 181)
    (= (flightcost cityB cityA) 188)
    (= (flightcost cityB cityD) 194)
    (= (flightcost cityB cityE) 135)
    (= (flightcost cityC cityA) 121)
    (= (flightcost cityC cityB) 143)
    (= (flightcost cityC cityE) 149)
    (= (flightcost cityD cityB) 104)
    (= (flightcost cityD cityC) 157)
    (= (flightcost cityD cityE) 117)
    (= (flightcost cityE cityB) 136)
    (= (flightcost cityE cityC) 133)
    (= (flightcost cityE cityD) 119)

  )

  (:goal
    (and
      (>= (citiesVisited) 5)
      (>= (totalDays) 15)
      (>= (totalcost) 100)
      (<= (totalcost) 100000)
    )
  )

  (:metric 
    minimize (totalcost)
  )

)
