(define (problem autogen)
  (:domain worldsEndAndBeyond)

  (:objects
    Origin cityA cityB cityC cityD cityE - city
    hotelA_A hotelA_B hotelB_A hotelB_B hotelC_A hotelC_B hotelD_A hotelD_B hotelE_A hotelE_B - hotel
  )

  (:init
    (currentLocation Origin)

    (hotelAt hotelA_A cityA)
    (hotelAt hotelA_B cityA)
    (hotelAt hotelB_A cityB)
    (hotelAt hotelB_B cityB)
    (hotelAt hotelC_A cityC)
    (hotelAt hotelC_B cityC)
    (hotelAt hotelD_A cityD)
    (hotelAt hotelD_B cityD)
    (hotelAt hotelE_A cityE)
    (hotelAt hotelE_B cityE)

    (flight Origin cityA)
    (flight Origin cityB)
    (flight Origin cityC)
    (flight Origin cityD)
    (flight Origin cityE)
    (flight cityA cityB)
    (flight cityA cityC)
    (flight cityA cityD)
    (flight cityB cityA)
    (flight cityB cityC)
    (flight cityB cityD)
    (flight cityC cityA)
    (flight cityC cityB)
    (flight cityC cityE)
    (flight cityD cityA)
    (flight cityD cityB)
    (flight cityD cityC)
    (flight cityE cityA)
    (flight cityE cityB)
    (flight cityE cityC)

    (= (citiesVisited) 0)
    (= (totalDays) 0)
    (= (minDaysInCity) 2)
    (= (maxDaysInCity) 2)

    (= (stayDuration Origin) 0)
    (= (stayDuration cityA) 0)
    (= (stayDuration cityB) 0)
    (= (stayDuration cityC) 0)
    (= (stayDuration cityD) 0)
    (= (stayDuration cityE) 0)
    (= (totalcost) 0)
    (= (hotelcost hotelA_A) 132)
    (= (hotelcost hotelA_B) 94)
    (= (hotelcost hotelB_A) 221)
    (= (hotelcost hotelB_B) 188)
    (= (hotelcost hotelC_A) 216)
    (= (hotelcost hotelC_B) 70)
    (= (hotelcost hotelD_A) 94)
    (= (hotelcost hotelD_B) 139)
    (= (hotelcost hotelE_A) 143)
    (= (hotelcost hotelE_B) 151)

    (= (flightcost Origin cityA) 0)
    (= (flightcost Origin cityB) 0)
    (= (flightcost Origin cityC) 0)
    (= (flightcost Origin cityD) 0)
    (= (flightcost Origin cityE) 0)
    (= (flightcost cityA cityB) 128)
    (= (flightcost cityA cityC) 118)
    (= (flightcost cityA cityD) 137)
    (= (flightcost cityB cityA) 195)
    (= (flightcost cityB cityC) 145)
    (= (flightcost cityB cityD) 166)
    (= (flightcost cityC cityA) 171)
    (= (flightcost cityC cityB) 150)
    (= (flightcost cityC cityE) 152)
    (= (flightcost cityD cityA) 171)
    (= (flightcost cityD cityB) 150)
    (= (flightcost cityD cityC) 172)
    (= (flightcost cityE cityA) 184)
    (= (flightcost cityE cityB) 164)
    (= (flightcost cityE cityC) 124)

  )

  (:goal
    (and
      (>= (citiesVisited) 4)
      (>= (totalDays) 4)
      (>= (totalcost) 100)
      (<= (totalcost) 1000000)
    )
  )

  (:metric 
    minimize (totalcost)
  )

)

