(define (problem autogen)
  (:domain worldsEndAndBeyond)

  (:objects
    Origin cityA cityB cityC cityD cityE cityF cityG cityH cityI cityJ cityK cityL cityM cityN cityO cityP cityQ cityR cityS cityT cityU cityV cityW cityX cityY - city
    hotelA_A hotelB_A hotelC_A hotelD_A hotelE_A hotelF_A hotelG_A hotelH_A hotelI_A hotelJ_A hotelK_A hotelL_A hotelM_A hotelN_A hotelO_A hotelP_A hotelQ_A hotelR_A hotelS_A hotelT_A hotelU_A hotelV_A hotelW_A hotelX_A hotelY_A - hotel
  )

  (:init
    (currentLocation Origin)

    (hotelAt hotelA_A cityA)
    (hotelAt hotelB_A cityB)
    (hotelAt hotelC_A cityC)
    (hotelAt hotelD_A cityD)
    (hotelAt hotelE_A cityE)
    (hotelAt hotelF_A cityF)
    (hotelAt hotelG_A cityG)
    (hotelAt hotelH_A cityH)
    (hotelAt hotelI_A cityI)
    (hotelAt hotelJ_A cityJ)
    (hotelAt hotelK_A cityK)
    (hotelAt hotelL_A cityL)
    (hotelAt hotelM_A cityM)
    (hotelAt hotelN_A cityN)
    (hotelAt hotelO_A cityO)
    (hotelAt hotelP_A cityP)
    (hotelAt hotelQ_A cityQ)
    (hotelAt hotelR_A cityR)
    (hotelAt hotelS_A cityS)
    (hotelAt hotelT_A cityT)
    (hotelAt hotelU_A cityU)
    (hotelAt hotelV_A cityV)
    (hotelAt hotelW_A cityW)
    (hotelAt hotelX_A cityX)
    (hotelAt hotelY_A cityY)

    (flight Origin cityA)
    (flight Origin cityB)
    (flight Origin cityC)
    (flight Origin cityD)
    (flight Origin cityE)
    (flight Origin cityF)
    (flight Origin cityG)
    (flight Origin cityH)
    (flight Origin cityI)
    (flight Origin cityJ)
    (flight Origin cityK)
    (flight Origin cityL)
    (flight Origin cityM)
    (flight Origin cityN)
    (flight Origin cityO)
    (flight Origin cityP)
    (flight Origin cityQ)
    (flight Origin cityR)
    (flight Origin cityS)
    (flight Origin cityT)
    (flight Origin cityU)
    (flight Origin cityV)
    (flight Origin cityW)
    (flight Origin cityX)
    (flight Origin cityY)
    (flight cityA cityR)
    (flight cityB cityW)
    (flight cityC cityG)
    (flight cityD cityA)
    (flight cityE cityW)
    (flight cityF cityS)
    (flight cityG cityU)
    (flight cityH cityX)
    (flight cityI cityR)
    (flight cityJ cityI)
    (flight cityK cityS)
    (flight cityL cityU)
    (flight cityM cityT)
    (flight cityN cityA)
    (flight cityO cityS)
    (flight cityP cityD)
    (flight cityQ cityV)
    (flight cityR cityS)
    (flight cityS cityV)
    (flight cityT cityY)
    (flight cityU cityK)
    (flight cityV cityG)
    (flight cityW cityK)
    (flight cityX cityD)
    (flight cityY cityM)

    (= (citiesVisited) 0)
    (= (totalDays) 0)
    (= (minDaysInCity) 1)
    (= (maxDaysInCity) 5)

    (= (stayDuration Origin) 0)
    (= (stayDuration cityA) 0)
    (= (stayDuration cityB) 0)
    (= (stayDuration cityC) 0)
    (= (stayDuration cityD) 0)
    (= (stayDuration cityE) 0)
    (= (stayDuration cityF) 0)
    (= (stayDuration cityG) 0)
    (= (stayDuration cityH) 0)
    (= (stayDuration cityI) 0)
    (= (stayDuration cityJ) 0)
    (= (stayDuration cityK) 0)
    (= (stayDuration cityL) 0)
    (= (stayDuration cityM) 0)
    (= (stayDuration cityN) 0)
    (= (stayDuration cityO) 0)
    (= (stayDuration cityP) 0)
    (= (stayDuration cityQ) 0)
    (= (stayDuration cityR) 0)
    (= (stayDuration cityS) 0)
    (= (stayDuration cityT) 0)
    (= (stayDuration cityU) 0)
    (= (stayDuration cityV) 0)
    (= (stayDuration cityW) 0)
    (= (stayDuration cityX) 0)
    (= (stayDuration cityY) 0)
    (= (totalcost) 0)
    (= (hotelcost hotelA_A) 199)
    (= (hotelcost hotelB_A) 239)
    (= (hotelcost hotelC_A) 146)
    (= (hotelcost hotelD_A) 51)
    (= (hotelcost hotelE_A) 70)
    (= (hotelcost hotelF_A) 238)
    (= (hotelcost hotelG_A) 75)
    (= (hotelcost hotelH_A) 228)
    (= (hotelcost hotelI_A) 215)
    (= (hotelcost hotelJ_A) 131)
    (= (hotelcost hotelK_A) 125)
    (= (hotelcost hotelL_A) 109)
    (= (hotelcost hotelM_A) 151)
    (= (hotelcost hotelN_A) 125)
    (= (hotelcost hotelO_A) 78)
    (= (hotelcost hotelP_A) 184)
    (= (hotelcost hotelQ_A) 170)
    (= (hotelcost hotelR_A) 73)
    (= (hotelcost hotelS_A) 55)
    (= (hotelcost hotelT_A) 195)
    (= (hotelcost hotelU_A) 141)
    (= (hotelcost hotelV_A) 136)
    (= (hotelcost hotelW_A) 116)
    (= (hotelcost hotelX_A) 161)
    (= (hotelcost hotelY_A) 134)

    (= (flightcost Origin cityA) 0)
    (= (flightcost Origin cityB) 0)
    (= (flightcost Origin cityC) 0)
    (= (flightcost Origin cityD) 0)
    (= (flightcost Origin cityE) 0)
    (= (flightcost Origin cityF) 0)
    (= (flightcost Origin cityG) 0)
    (= (flightcost Origin cityH) 0)
    (= (flightcost Origin cityI) 0)
    (= (flightcost Origin cityJ) 0)
    (= (flightcost Origin cityK) 0)
    (= (flightcost Origin cityL) 0)
    (= (flightcost Origin cityM) 0)
    (= (flightcost Origin cityN) 0)
    (= (flightcost Origin cityO) 0)
    (= (flightcost Origin cityP) 0)
    (= (flightcost Origin cityQ) 0)
    (= (flightcost Origin cityR) 0)
    (= (flightcost Origin cityS) 0)
    (= (flightcost Origin cityT) 0)
    (= (flightcost Origin cityU) 0)
    (= (flightcost Origin cityV) 0)
    (= (flightcost Origin cityW) 0)
    (= (flightcost Origin cityX) 0)
    (= (flightcost Origin cityY) 0)
    (= (flightcost cityA cityR) 141)
    (= (flightcost cityB cityW) 171)
    (= (flightcost cityC cityG) 141)
    (= (flightcost cityD cityA) 128)
    (= (flightcost cityE cityW) 124)
    (= (flightcost cityF cityS) 105)
    (= (flightcost cityG cityU) 178)
    (= (flightcost cityH cityX) 165)
    (= (flightcost cityI cityR) 101)
    (= (flightcost cityJ cityI) 179)
    (= (flightcost cityK cityS) 137)
    (= (flightcost cityL cityU) 141)
    (= (flightcost cityM cityT) 156)
    (= (flightcost cityN cityA) 115)
    (= (flightcost cityO cityS) 159)
    (= (flightcost cityP cityD) 137)
    (= (flightcost cityQ cityV) 143)
    (= (flightcost cityR cityS) 170)
    (= (flightcost cityS cityV) 138)
    (= (flightcost cityT cityY) 170)
    (= (flightcost cityU cityK) 198)
    (= (flightcost cityV cityG) 124)
    (= (flightcost cityW cityK) 191)
    (= (flightcost cityX cityD) 122)
    (= (flightcost cityY cityM) 181)

  )

  (:goal
    (and
      (>= (citiesVisited) 9)
      (>= (totalDays) 40)
      (>= (totalcost) 100)
      (<= (totalcost) 10000000)
    )
  )

  (:metric 
    minimize (totalcost)
  )

)
