(define (problem autogen)
  (:domain worldsEndAndBeyond)

  (:objects
    Origin cityA cityB cityC cityD cityE cityF cityG cityH cityI cityJ cityK cityL cityM cityN cityO - city
    hotelA_A hotelA_B hotelA_C hotelB_A hotelB_B hotelB_C hotelC_A hotelC_B hotelC_C hotelD_A hotelD_B hotelD_C hotelE_A hotelE_B hotelE_C hotelF_A hotelF_B hotelF_C hotelG_A hotelG_B hotelG_C hotelH_A hotelH_B hotelH_C hotelI_A hotelI_B hotelI_C hotelJ_A hotelJ_B hotelJ_C hotelK_A hotelK_B hotelK_C hotelL_A hotelL_B hotelL_C hotelM_A hotelM_B hotelM_C hotelN_A hotelN_B hotelN_C hotelO_A hotelO_B hotelO_C - hotel
  )

  (:init
    (currentLocation Origin)

    (hotelAt hotelA_A cityA)
    (hotelAt hotelA_B cityA)
    (hotelAt hotelA_C cityA)
    (hotelAt hotelB_A cityB)
    (hotelAt hotelB_B cityB)
    (hotelAt hotelB_C cityB)
    (hotelAt hotelC_A cityC)
    (hotelAt hotelC_B cityC)
    (hotelAt hotelC_C cityC)
    (hotelAt hotelD_A cityD)
    (hotelAt hotelD_B cityD)
    (hotelAt hotelD_C cityD)
    (hotelAt hotelE_A cityE)
    (hotelAt hotelE_B cityE)
    (hotelAt hotelE_C cityE)
    (hotelAt hotelF_A cityF)
    (hotelAt hotelF_B cityF)
    (hotelAt hotelF_C cityF)
    (hotelAt hotelG_A cityG)
    (hotelAt hotelG_B cityG)
    (hotelAt hotelG_C cityG)
    (hotelAt hotelH_A cityH)
    (hotelAt hotelH_B cityH)
    (hotelAt hotelH_C cityH)
    (hotelAt hotelI_A cityI)
    (hotelAt hotelI_B cityI)
    (hotelAt hotelI_C cityI)
    (hotelAt hotelJ_A cityJ)
    (hotelAt hotelJ_B cityJ)
    (hotelAt hotelJ_C cityJ)
    (hotelAt hotelK_A cityK)
    (hotelAt hotelK_B cityK)
    (hotelAt hotelK_C cityK)
    (hotelAt hotelL_A cityL)
    (hotelAt hotelL_B cityL)
    (hotelAt hotelL_C cityL)
    (hotelAt hotelM_A cityM)
    (hotelAt hotelM_B cityM)
    (hotelAt hotelM_C cityM)
    (hotelAt hotelN_A cityN)
    (hotelAt hotelN_B cityN)
    (hotelAt hotelN_C cityN)
    (hotelAt hotelO_A cityO)
    (hotelAt hotelO_B cityO)
    (hotelAt hotelO_C cityO)

    (flight Origin cityA)
    (flight Origin cityB)
    (flight Origin cityC)
    (flight Origin cityD)
    (flight Origin cityE)
    (flight Origin cityF)
    (flight Origin cityG)
    (flight Origin cityH)
    (flight Origin cityI)
    (flight Origin cityJ)
    (flight Origin cityK)
    (flight Origin cityL)
    (flight Origin cityM)
    (flight Origin cityN)
    (flight Origin cityO)
    (flight cityA cityF)
    (flight cityA cityH)
    (flight cityA cityK)
    (flight cityB cityJ)
    (flight cityB cityL)
    (flight cityB cityM)
    (flight cityC cityE)
    (flight cityC cityI)
    (flight cityC cityK)
    (flight cityD cityE)
    (flight cityD cityG)
    (flight cityD cityO)
    (flight cityE cityC)
    (flight cityE cityJ)
    (flight cityE cityL)
    (flight cityF cityB)
    (flight cityF cityE)
    (flight cityF cityO)
    (flight cityG cityA)
    (flight cityG cityD)
    (flight cityG cityF)
    (flight cityH cityE)
    (flight cityH cityF)
    (flight cityH cityK)
    (flight cityI cityC)
    (flight cityI cityN)
    (flight cityI cityO)
    (flight cityJ cityA)
    (flight cityJ cityF)
    (flight cityJ cityN)
    (flight cityK cityB)
    (flight cityK cityJ)
    (flight cityK cityN)
    (flight cityL cityF)
    (flight cityL cityJ)
    (flight cityL cityM)
    (flight cityM cityC)
    (flight cityM cityD)
    (flight cityM cityL)
    (flight cityN cityI)
    (flight cityN cityK)
    (flight cityN cityL)
    (flight cityO cityB)
    (flight cityO cityI)
    (flight cityO cityJ)

    (= (citiesVisited) 0)
    (= (totalDays) 0)
    (= (minDaysInCity) 2)
    (= (maxDaysInCity) 4)

    (= (stayDuration Origin) 0)
    (= (stayDuration cityA) 0)
    (= (stayDuration cityB) 0)
    (= (stayDuration cityC) 0)
    (= (stayDuration cityD) 0)
    (= (stayDuration cityE) 0)
    (= (stayDuration cityF) 0)
    (= (stayDuration cityG) 0)
    (= (stayDuration cityH) 0)
    (= (stayDuration cityI) 0)
    (= (stayDuration cityJ) 0)
    (= (stayDuration cityK) 0)
    (= (stayDuration cityL) 0)
    (= (stayDuration cityM) 0)
    (= (stayDuration cityN) 0)
    (= (stayDuration cityO) 0)
    (= (totalcost) 0)
    (= (hotelcost hotelA_A) 63)
    (= (hotelcost hotelA_B) 196)
    (= (hotelcost hotelA_C) 147)
    (= (hotelcost hotelB_A) 108)
    (= (hotelcost hotelB_B) 103)
    (= (hotelcost hotelB_C) 233)
    (= (hotelcost hotelC_A) 204)
    (= (hotelcost hotelC_B) 178)
    (= (hotelcost hotelC_C) 110)
    (= (hotelcost hotelD_A) 209)
    (= (hotelcost hotelD_B) 183)
    (= (hotelcost hotelD_C) 63)
    (= (hotelcost hotelE_A) 201)
    (= (hotelcost hotelE_B) 82)
    (= (hotelcost hotelE_C) 62)
    (= (hotelcost hotelF_A) 55)
    (= (hotelcost hotelF_B) 193)
    (= (hotelcost hotelF_C) 142)
    (= (hotelcost hotelG_A) 89)
    (= (hotelcost hotelG_B) 240)
    (= (hotelcost hotelG_C) 186)
    (= (hotelcost hotelH_A) 178)
    (= (hotelcost hotelH_B) 56)
    (= (hotelcost hotelH_C) 165)
    (= (hotelcost hotelI_A) 233)
    (= (hotelcost hotelI_B) 146)
    (= (hotelcost hotelI_C) 87)
    (= (hotelcost hotelJ_A) 168)
    (= (hotelcost hotelJ_B) 212)
    (= (hotelcost hotelJ_C) 192)
    (= (hotelcost hotelK_A) 210)
    (= (hotelcost hotelK_B) 178)
    (= (hotelcost hotelK_C) 90)
    (= (hotelcost hotelL_A) 107)
    (= (hotelcost hotelL_B) 188)
    (= (hotelcost hotelL_C) 143)
    (= (hotelcost hotelM_A) 90)
    (= (hotelcost hotelM_B) 143)
    (= (hotelcost hotelM_C) 224)
    (= (hotelcost hotelN_A) 103)
    (= (hotelcost hotelN_B) 102)
    (= (hotelcost hotelN_C) 157)
    (= (hotelcost hotelO_A) 68)
    (= (hotelcost hotelO_B) 53)
    (= (hotelcost hotelO_C) 142)

    (= (flightcost Origin cityA) 0)
    (= (flightcost Origin cityB) 0)
    (= (flightcost Origin cityC) 0)
    (= (flightcost Origin cityD) 0)
    (= (flightcost Origin cityE) 0)
    (= (flightcost Origin cityF) 0)
    (= (flightcost Origin cityG) 0)
    (= (flightcost Origin cityH) 0)
    (= (flightcost Origin cityI) 0)
    (= (flightcost Origin cityJ) 0)
    (= (flightcost Origin cityK) 0)
    (= (flightcost Origin cityL) 0)
    (= (flightcost Origin cityM) 0)
    (= (flightcost Origin cityN) 0)
    (= (flightcost Origin cityO) 0)
    (= (flightcost cityA cityF) 130)
    (= (flightcost cityA cityH) 161)
    (= (flightcost cityA cityK) 187)
    (= (flightcost cityB cityJ) 174)
    (= (flightcost cityB cityL) 100)
    (= (flightcost cityB cityM) 177)
    (= (flightcost cityC cityE) 163)
    (= (flightcost cityC cityI) 180)
    (= (flightcost cityC cityK) 183)
    (= (flightcost cityD cityE) 178)
    (= (flightcost cityD cityG) 115)
    (= (flightcost cityD cityO) 132)
    (= (flightcost cityE cityC) 167)
    (= (flightcost cityE cityJ) 134)
    (= (flightcost cityE cityL) 146)
    (= (flightcost cityF cityB) 109)
    (= (flightcost cityF cityE) 146)
    (= (flightcost cityF cityO) 174)
    (= (flightcost cityG cityA) 149)
    (= (flightcost cityG cityD) 103)
    (= (flightcost cityG cityF) 113)
    (= (flightcost cityH cityE) 195)
    (= (flightcost cityH cityF) 195)
    (= (flightcost cityH cityK) 158)
    (= (flightcost cityI cityC) 169)
    (= (flightcost cityI cityN) 100)
    (= (flightcost cityI cityO) 162)
    (= (flightcost cityJ cityA) 176)
    (= (flightcost cityJ cityF) 118)
    (= (flightcost cityJ cityN) 118)
    (= (flightcost cityK cityB) 120)
    (= (flightcost cityK cityJ) 101)
    (= (flightcost cityK cityN) 131)
    (= (flightcost cityL cityF) 107)
    (= (flightcost cityL cityJ) 127)
    (= (flightcost cityL cityM) 183)
    (= (flightcost cityM cityC) 184)
    (= (flightcost cityM cityD) 142)
    (= (flightcost cityM cityL) 164)
    (= (flightcost cityN cityI) 120)
    (= (flightcost cityN cityK) 121)
    (= (flightcost cityN cityL) 179)
    (= (flightcost cityO cityB) 104)
    (= (flightcost cityO cityI) 188)
    (= (flightcost cityO cityJ) 165)

  )

  (:goal
    (and
      (>= (citiesVisited) 12)
      (>= (totalDays) 20)
      (>= (totalcost) 2000)
      (<= (totalcost) 4000)
    )
  )

  (:metric 
    minimize (totalcost)
  )

)
