(define (problem autogen)
  (:domain worldsEndAndBeyond)

  (:objects
    Origin cityA cityB cityC cityD cityE cityF cityG cityH cityI cityJ cityK cityL - city
    hotelA_A hotelA_B hotelB_A hotelB_B hotelC_A hotelC_B hotelD_A hotelD_B hotelE_A hotelE_B hotelF_A hotelF_B hotelG_A hotelG_B hotelH_A hotelH_B hotelI_A hotelI_B hotelJ_A hotelJ_B hotelK_A hotelK_B hotelL_A hotelL_B - hotel
  )

  (:init
    (currentLocation Origin)

    (hotelAt hotelA_A cityA)
    (hotelAt hotelA_B cityA)
    (hotelAt hotelB_A cityB)
    (hotelAt hotelB_B cityB)
    (hotelAt hotelC_A cityC)
    (hotelAt hotelC_B cityC)
    (hotelAt hotelD_A cityD)
    (hotelAt hotelD_B cityD)
    (hotelAt hotelE_A cityE)
    (hotelAt hotelE_B cityE)
    (hotelAt hotelF_A cityF)
    (hotelAt hotelF_B cityF)
    (hotelAt hotelG_A cityG)
    (hotelAt hotelG_B cityG)
    (hotelAt hotelH_A cityH)
    (hotelAt hotelH_B cityH)
    (hotelAt hotelI_A cityI)
    (hotelAt hotelI_B cityI)
    (hotelAt hotelJ_A cityJ)
    (hotelAt hotelJ_B cityJ)
    (hotelAt hotelK_A cityK)
    (hotelAt hotelK_B cityK)
    (hotelAt hotelL_A cityL)
    (hotelAt hotelL_B cityL)

    (flight Origin cityA)
    (flight Origin cityB)
    (flight Origin cityC)
    (flight Origin cityD)
    (flight Origin cityE)
    (flight Origin cityF)
    (flight Origin cityG)
    (flight Origin cityH)
    (flight Origin cityI)
    (flight Origin cityJ)
    (flight Origin cityK)
    (flight Origin cityL)
    (flight cityA cityG)
    (flight cityA cityJ)
    (flight cityA cityK)
    (flight cityA cityL)
    (flight cityB cityA)
    (flight cityB cityD)
    (flight cityB cityF)
    (flight cityB cityL)
    (flight cityC cityA)
    (flight cityC cityD)
    (flight cityC cityE)
    (flight cityC cityL)
    (flight cityD cityE)
    (flight cityD cityI)
    (flight cityD cityK)
    (flight cityD cityL)
    (flight cityE cityB)
    (flight cityE cityC)
    (flight cityE cityG)
    (flight cityE cityJ)
    (flight cityF cityA)
    (flight cityF cityB)
    (flight cityF cityH)
    (flight cityF cityK)
    (flight cityG cityB)
    (flight cityG cityD)
    (flight cityG cityJ)
    (flight cityG cityK)
    (flight cityH cityB)
    (flight cityH cityG)
    (flight cityH cityI)
    (flight cityH cityL)
    (flight cityI cityC)
    (flight cityI cityD)
    (flight cityI cityJ)
    (flight cityI cityL)
    (flight cityJ cityC)
    (flight cityJ cityE)
    (flight cityJ cityF)
    (flight cityJ cityH)
    (flight cityK cityB)
    (flight cityK cityE)
    (flight cityK cityF)
    (flight cityK cityH)
    (flight cityL cityD)
    (flight cityL cityE)
    (flight cityL cityF)
    (flight cityL cityH)

    (= (citiesVisited) 0)
    (= (totalDays) 0)
    (= (minDaysInCity) 1)
    (= (maxDaysInCity) 2)

    (= (stayDuration Origin) 0)
    (= (stayDuration cityA) 0)
    (= (stayDuration cityB) 0)
    (= (stayDuration cityC) 0)
    (= (stayDuration cityD) 0)
    (= (stayDuration cityE) 0)
    (= (stayDuration cityF) 0)
    (= (stayDuration cityG) 0)
    (= (stayDuration cityH) 0)
    (= (stayDuration cityI) 0)
    (= (stayDuration cityJ) 0)
    (= (stayDuration cityK) 0)
    (= (stayDuration cityL) 0)
    (= (totalcost) 0)
    (= (hotelcost hotelA_A) 210)
    (= (hotelcost hotelA_B) 208)
    (= (hotelcost hotelB_A) 112)
    (= (hotelcost hotelB_B) 91)
    (= (hotelcost hotelC_A) 53)
    (= (hotelcost hotelC_B) 68)
    (= (hotelcost hotelD_A) 241)
    (= (hotelcost hotelD_B) 55)
    (= (hotelcost hotelE_A) 207)
    (= (hotelcost hotelE_B) 232)
    (= (hotelcost hotelF_A) 161)
    (= (hotelcost hotelF_B) 206)
    (= (hotelcost hotelG_A) 91)
    (= (hotelcost hotelG_B) 207)
    (= (hotelcost hotelH_A) 109)
    (= (hotelcost hotelH_B) 201)
    (= (hotelcost hotelI_A) 63)
    (= (hotelcost hotelI_B) 73)
    (= (hotelcost hotelJ_A) 138)
    (= (hotelcost hotelJ_B) 104)
    (= (hotelcost hotelK_A) 137)
    (= (hotelcost hotelK_B) 178)
    (= (hotelcost hotelL_A) 83)
    (= (hotelcost hotelL_B) 234)

    (= (flightcost Origin cityA) 0)
    (= (flightcost Origin cityB) 0)
    (= (flightcost Origin cityC) 0)
    (= (flightcost Origin cityD) 0)
    (= (flightcost Origin cityE) 0)
    (= (flightcost Origin cityF) 0)
    (= (flightcost Origin cityG) 0)
    (= (flightcost Origin cityH) 0)
    (= (flightcost Origin cityI) 0)
    (= (flightcost Origin cityJ) 0)
    (= (flightcost Origin cityK) 0)
    (= (flightcost Origin cityL) 0)
    (= (flightcost cityA cityG) 107)
    (= (flightcost cityA cityJ) 118)
    (= (flightcost cityA cityK) 172)
    (= (flightcost cityA cityL) 105)
    (= (flightcost cityB cityA) 150)
    (= (flightcost cityB cityD) 108)
    (= (flightcost cityB cityF) 164)
    (= (flightcost cityB cityL) 162)
    (= (flightcost cityC cityA) 118)
    (= (flightcost cityC cityD) 178)
    (= (flightcost cityC cityE) 156)
    (= (flightcost cityC cityL) 173)
    (= (flightcost cityD cityE) 196)
    (= (flightcost cityD cityI) 147)
    (= (flightcost cityD cityK) 178)
    (= (flightcost cityD cityL) 153)
    (= (flightcost cityE cityB) 181)
    (= (flightcost cityE cityC) 141)
    (= (flightcost cityE cityG) 161)
    (= (flightcost cityE cityJ) 122)
    (= (flightcost cityF cityA) 150)
    (= (flightcost cityF cityB) 173)
    (= (flightcost cityF cityH) 125)
    (= (flightcost cityF cityK) 164)
    (= (flightcost cityG cityB) 196)
    (= (flightcost cityG cityD) 113)
    (= (flightcost cityG cityJ) 118)
    (= (flightcost cityG cityK) 183)
    (= (flightcost cityH cityB) 193)
    (= (flightcost cityH cityG) 104)
    (= (flightcost cityH cityI) 119)
    (= (flightcost cityH cityL) 101)
    (= (flightcost cityI cityC) 174)
    (= (flightcost cityI cityD) 143)
    (= (flightcost cityI cityJ) 158)
    (= (flightcost cityI cityL) 176)
    (= (flightcost cityJ cityC) 103)
    (= (flightcost cityJ cityE) 174)
    (= (flightcost cityJ cityF) 139)
    (= (flightcost cityJ cityH) 121)
    (= (flightcost cityK cityB) 152)
    (= (flightcost cityK cityE) 147)
    (= (flightcost cityK cityF) 146)
    (= (flightcost cityK cityH) 100)
    (= (flightcost cityL cityD) 194)
    (= (flightcost cityL cityE) 124)
    (= (flightcost cityL cityF) 105)
    (= (flightcost cityL cityH) 175)

  )

  (:goal
    (and
      (>= (citiesVisited) 6)
      (>= (totalDays) 20)
      (>= (totalcost) 1500)
      (<= (totalcost) 2000)
    )
  )

  (:metric 
    minimize (totalcost)
  )

)
